Blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Blog"

urlpatterns = [
    path('', views.home_page,name='home_page'),
    path('email_newsletter/',views.emailNewsletter,name='email'),
    path('blog_page/',views.blog_page,name='blog_page'),
    path('blog_detail/<slug:slug>/',views.blog_detail,name='blog_detail'),
    path('search/', views.search, name='search'),
    path('add_comment/',views.add_comment,name='add_comment'),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('category/<slug:slug>/', views.blog_by_category, name='blog_by_category'),
    path('destination/<slug:slug>/', views.blog_by_destination, name='blog_by_destination'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('',include('Blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from tinymce import models as tinymce_models
from tinymce.models import HTMLField


# Category Model
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=100, blank=True, null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='subcategories', blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'

# Destination Model
class Destination(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='destination_images/',blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=100, blank=True, null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_destinations', blank=True, null=True)
    is_featured_destination = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Destinations'

# Slider Model
class Slider(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='sliders/')

    def __str__(self):
        return self.title


class AboutUs(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='about_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.pk and AboutUs.objects.exists():
            raise ValidationError('There is already an AboutUs instance. Only one instance is allowed.')
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'About Us'
  
class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=200, blank=True, null=True)
    content = tinymce_models.HTMLField()
    published_date = models.DateTimeField(auto_now_add=True)
    is_popular_guide = models.BooleanField(default=False)
    featured_image = models.ForeignKey('BlogPostImage', related_name='featured_image', null=True, blank=True, on_delete=models.SET_NULL)
    popular_image = models.ForeignKey('BlogPostImage', related_name='popular_image', null=True, blank=True, on_delete=models.SET_NULL)
    main_image = models.ImageField(upload_to='blog_images/')
    category = models.ForeignKey(Category, null=True,blank=True, on_delete=models.CASCADE, related_name='blog_posts')
    destination = models.ForeignKey(Destination, null=True,blank=True, on_delete=models.CASCADE, related_name='blog_posts_destination')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class BlogPostImage(models.Model):
    blog_post = models.ForeignKey(BlogPost, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog_images/')
    is_featured = models.BooleanField(default=False)  # Mark image as featured if needed

    def __str__(self):
        return f"Image for {self.blog_post.title}"    
    
class BlogPageBackgroundImage(models.Model):
    image = models.ImageField(upload_to='blog_images/')
    
    def save(self, *args, **kwargs):
        if not self.pk and BlogPageBackgroundImage.objects.exists():
            raise ValidationError('There is already a Background Image instance. Only one instance is allowed.')
        return super().save(*args, **kwargs)
    
    
class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    comment_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def children(self):
        """Returns replies to the comment."""
        return self.replies.all()

    @property
    def is_reply(self):
        """Returns True if this comment is a reply to another comment."""
        return self.parent is not None
    
    
    
class ContactInfo(models.Model):
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    business_hours = models.CharField(max_length=100)
    

    def __str__(self):
        return f"Contact Info"
    
    def save(self, *args, **kwargs):
        if not self.pk and ContactInfo.objects.exists():
            raise ValidationError('There is already an Contactinfo instance. Only one instance is allowed.')
        return super().save(*args, **kwargs)
    
    
    
    
class ContactFormSubmission(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} ({self.email})"
    


class EmailNewsletter(models.Model):
    email = models.EmailField(unique=True)
    
    def __str__(self):
        return self.email

Blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.http import JsonResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.validators import validate_email
import os


# Create your views here.
def home_page(request):
      carousel = Slider.objects.all()
      about_content = AboutUs.objects.first()
      latest_posts = BlogPost.objects.order_by('-published_date')[:5]
      print(f'this is latest post {latest_posts}')
      popular_guides = BlogPost.objects.filter(is_popular_guide=True)
      featured_destinations = Destination.objects.filter(is_featured_destination=True)
      first_four_destinations = featured_destinations[:4]
      remaining_destinations = featured_destinations[4:]
      
      context = {
            'carousel':carousel,
            'about':about_content,
            'latest_posts': latest_posts,
            'popular_guides': popular_guides,
            'featured_destinations': featured_destinations,
            'first_four_destinations': first_four_destinations,
            'remaining_destinations': remaining_destinations,
      }
      
      return render(request,'Blog/home.html',context)
  
def blog_page(request):
    blog_list = BlogPost.objects.all()
    print(f'this is blog list {blog_list}')
    paginator = Paginator(blog_list, 5)  # Show 10 blogs per page

    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page.
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver the last page of results.
        page_obj = paginator.page(paginator.num_pages)
    
    print(f'this is page object {page_obj}')
    background_image = BlogPageBackgroundImage.objects.first()
    context = {
        'page_obj': page_obj,  # Pass page_obj to the context
        'background_image': background_image,
    }
    return render(request, 'Blog/blog.html', context)



# def blog_detail(request,slug):
#       blog = get_object_or_404(BlogPost,slug=slug)
#       popular_guides = BlogPost.objects.filter(is_popular_guide=True)
#       background_image = BlogPageBackgroundImage.objects.first()
#       comments = Comment.objects.filter(post = blog)
#       print('view runs here')
#       context = {
#             'blog':blog,
#             'popular_guides':popular_guides,
#             'background_image':background_image,
#             'comments':comments
#       }
#       return render(request,'Blog/blog_detail.html',context)

def blog_detail(request, slug):
    blog = get_object_or_404(BlogPost.objects.prefetch_related('comments'), slug=slug)
    popular_guides = BlogPost.objects.filter(is_popular_guide=True)
    background_image = BlogPageBackgroundImage.objects.first()
    
    context = {
        'blog': blog,
        'popular_guides': popular_guides,
        'background_image': background_image,
        'comments': blog.comments.all()  # Using prefetch_related
    }
    return render(request, 'Blog/blog_detail.html', context)
  
  
def search(request):
    query = request.GET.get('query')
    
    if query:
        blogs = BlogPost.objects.filter(title__icontains=query)
    else:
        blogs = BlogPost.objects.none()  # No results if no query

    paginator = Paginator(blogs, 4)  # Show 10 blogs per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)  # Simplified handling

    background_image = BlogPageBackgroundImage.objects.first()
    
    context = {
        'blogs':blogs,
        'page_obj': page_obj,  # Pass page_obj to the context
        'query': query,
        'is_search': bool(query),  # Set is_search based on whether there is a query
        'background_image': background_image,
    }
    
    return render(request, 'Blog/blog.html', context)
    
def about(request):
      about_content = AboutUs.objects.first()
      context ={
            'about':about_content
      }
      return render(request,'Blog/about.html',context)

def contact(request):
    if request.method == 'GET':
        c_info = ContactInfo.objects.first()
        context = {
            'c_info': c_info,
        }
        return render(request, 'Blog/contact.html', context)
    
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        if not name or not email or not message:
            # Add an error message
            messages.error(request, 'Please fill in all required fields.')
            # Redirect back to the contact page
            return redirect('contact')  # Replace 'contact' with your URL name if different
        
        # Save the form data
        ContactFormSubmission.objects.create(
            name=name,
            email=email,
            phone=phone,
            message=message
        )
        
        # Add a success message
        messages.success(request, 'Thank you for your message! We will get back to you soon.')
        # Redirect back to the contact page
        return redirect('Blog:contact')  # Replace 'contact' with your URL name if different
  
  
def blog_by_category(request, slug):
    # Fetch blogs based on the category (logic not shown here)
    print(slug)
    cate = get_object_or_404(Category, slug=slug)
    background_image = BlogPageBackgroundImage.objects.first()
    page_obj = BlogPost.objects.filter(category=cate)
    context = {
        'heading': slug,
        'page_obj': page_obj,  # Replace with actual blog fetching logic
        'background_image':background_image,
    }
    return render(request, 'Blog/blog.html', context)

def blog_by_destination(request, slug):
    # Fetch blogs based on the destination (logic not shown here)
    dest = get_object_or_404(Destination, slug=slug)
    background_image = BlogPageBackgroundImage.objects.first()
    page_obj = BlogPost.objects.filter(destination=dest)
    context = {
        'heading': slug,
        'background_image':background_image,
        'page_obj': page_obj,  # Replace with actual blog fetching logic
    }
    return render(request, 'Blog/blog.html', context)



def add_comment(request):
      post_id = request.POST.get('post_id')
      comment_text = request.POST.get('comment')
      name = request.POST.get('name')
      email = request.POST.get('email')
      comment_id = request.POST.get('comment_id')  # To check if it's a reply

      if not post_id or not comment_text or not name or not email:
        return JsonResponse({'error': 'All fields are required.'}, status=400)

      try:
        post = BlogPost.objects.get(id=post_id)
      except BlogPost.DoesNotExist:
        return JsonResponse({'error': 'Invalid post.'}, status=400)

      if comment_id:
        try:
            parent_comment = Comment.objects.get(id=comment_id)
        except Comment.DoesNotExist:
            return JsonResponse({'error': 'Invalid parent comment.'}, status=400)
        # Create reply
        comment = Comment.objects.create(
            post=post,
            comment_text=comment_text,
            name=name,
            email=email,
            parent=parent_comment  # Assuming your Comment model has a parent field
        )
      else:
        # Create a new comment
        comment = Comment.objects.create(
            post=post,
            comment_text=comment_text,
            name=name,
            email=email
        )

      comment.save()
      return JsonResponse({'message': 'Comment submitted successfully!','comment_id': comment.id }, status=200)

      return JsonResponse({'error': 'Invalid request.'}, status=400)

   
def emailNewsletter(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        
        # Basic email validation
        try:
            validate_email(email)
        except ValidationError:
            return JsonResponse({'error': 'Invalid email address'}, status=400)
        
        # Check if email already exists
        if EmailNewsletter.objects.filter(email=email).exists():
            return JsonResponse({'error': 'Email already subscribed'}, status=400)
        
        # Save the email address
        obj = EmailNewsletter(email=email)
        obj.save()
        
        return JsonResponse({'message': 'Added successfully'})
    
    return JsonResponse({'error': 'Invalid request method'}, status=405)

Blog/templates/Blog/home.html
{% extends "base.html" %} {% load static %} 
{% block css %}
<link rel="stylesheet" href="{% static "Blog/css/home.css" %}">
{% endblock css %} 
{% block content %}


<!-- Slider section -->
<div id="carouselExampleSlidesOnly" class="carousel slide" style="margin-top: 70px" data-bs-ride="carousel">
  <div class="carousel-inner">

    {% if carousel %}
    {% for item in carousel %}
    <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="3000">
      <img
        src="{{item.image.url}}"
        class="d-block w-100"
        alt="..."
      />
      <div class="carousel-caption">
        <h5 class="cap">{{item.title}}</h5>
        <p>{{item.description}}</p>
      </div>
    </div>
    {% endfor %}

    {% else %}
    <div class="carousel-item active" data-bs-interval="3000">
      <img
        src="{% static 'Blog/images/image3_compress.jpg' %}"
        class="d-block w-100"
        alt="..."
        loading="lazy"
      />
      <div class="carousel-caption">
        <h5 class="cap">Enjoy. Travel. Experience</h5>
        <p>Discover the world’s best-kept secrets with our exclusive guides to breathtaking hidden gems and enchanting locales</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img
        src="{% static 'Blog/images/image2_compress.jpg' %}"
        class="d-block w-100"
        alt="..."
      />
      <div class="carousel-caption">
        <h5 class="cap">Enjoy. Travel. Experience</h5>
        <p>Discover the world’s best-kept secrets with our exclusive guides to breathtaking hidden gems and enchanting locales</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="1000">
      <img
        src="{% static 'Blog/images/image1_compress.jpg' %}"
        class="d-block w-100"
        alt="..."
      />
      <div class="carousel-caption">
        <h5 class="cap">Enjoy. Travel. Experience</h5>
        <p>Discover the world’s best-kept secrets with our exclusive guides to breathtaking hidden gems and enchanting locales</p>
      </div>
    </div>
    {% endif %}
  </div>
</div>

<!-- About Us Section -->
<div class="container mt-5">
  <div class="row g-4">
    {% if about %}
    <div class="col-md-6 d-flex align-items-center justify-content-center">
      <img src="{{about.image.url}}" class="img-fluid m-auto" style="height: auto; width: 100%; object-fit: cover;" alt="" loading="lazy">
      
    </div>
    <div class="col-md-6">
      <h3 class="heading">{{about.title}}</h3>
      <p class="f mt-2">
         {{about.description|linebreaksbr}}
      </p>
      <!-- <button class="button btn btn-primary">Read More</button> -->
    </div>
    {% else %}
    
    <div class="col-md-6 d-flex align-items-center justify-content-center">
      <img src="{% static 'Blog/images/ath_compress.jpg' %}" class="img-fluid m-auto" style="height: 400px; width: 100%; object-fit: cover;" alt="">
      
    </div>
    <div class="col-md-6">
      <h3 class="heading">About Us</h3>
      <p class="f mt-2">
          We are Rumvia, the person behind this website. I'm an adventurer who has been traveling the world full-time for 8 years now.
          <br><br>
          I started this travel blog in 2019 to document my international trips, share my photos, and help others learn how to explore the world and discover hidden gems.
          <br><br>
          I'm currently based in Bali, Indonesia, where I met my wife Intan, who’s a Bali local. Now she joins me on these wild and crazy adventures too.
          <br><br>
          Together, we've done some bucket list hikes, climbed active volcanoes, seen exotic wildlife, and visited some spectacular castles, temples, and monuments around the world.
          <br><br>
          I've worked with and been featured by BBC Travel, NBC News, Time, and other notable organizations.
          <br><br>
          I haven’t been everywhere, but it’s on my list. I hope this world travel blog can help and inspire you in your own journeys as well!
      </p>
      <!-- <button class="button btn btn-primary">Read More</button> -->
    </div>
    {% endif %}
  </div>
</div>


 <!-- Featured Destinations -->
<div class="heading-container mt-5 mb-5">
      <h1 class="heading">Featured Destinations</h1>
</div>
<div class="container">
      <div class="row gx-4 gy-3">
        {% if first_four_destinations %}
        {% for destination in first_four_destinations %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                <a href="{% url 'Blog:blog_by_destination' destination.slug %}" class="text-underline-none">
                    <div class="card">
                      
                      {% if destination.image %}
                        
                      <img src="{{destination.image.url}}" class="card-img-top-guides" alt="{{ destination.name }}" loading="lazy">
                      {% else %}
                        <p>No image found</p>
                      {% endif %}
                        
                        <button class="btn">{{ destination.name }}</button>
                    </div>
                </a>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-center p-5">No featured destinations available.</p>
    {% endif %}
</div>
<div class="my-class">
  <div class="swiper mySwiper">
    <div class="swiper-wrapper">
      {% if remaining_destinations %}
              {% for destination in remaining_destinations %}
                  <div class="swiper-slide">   
                    <div class="child-div">
                      <a href="{% url 'Blog:blog_by_destination' destination.slug %}"></a>
                      <img src="{{destination.image.url}}" alt="{{ destination.name }}" class="circle-img" loading="lazy">
                      <p class="text">{{ destination.name }}</p>
                    </div>   
                  </div>
                  <div class="swiper-slide">
                    <div class="child-div">
                  <img src="{% static 'Blog/images/image3_compress.jpg' %}" alt="Image 1" class="circle-img">
                  <p class="text">Text 1</p>
                </div>
              </div>
              {% endfor %}
          {% else %}
            
          {% endif %}

    </div>
    <div class="swiper-pagination"></div>
  </div>
</div>
      </div>
</div>


 <!-- Latest Post -->
<div class="heading-container mt-5 mb-5">
      <h1 class="heading">Latest post</h1>
</div>
<div class="container">
      <div class="row g-4">
        {% if latest_posts %}
        {% for post in latest_posts %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-4">
          <a href="{% url 'Blog:blog_detail'  post.slug %}" class="text-underline-none">
            <div class="card custom-card">
              <img src="{{post.main_image.url}}" class="card-img-top" alt="..." loading="lazy">
              <div class="card-body">
                <p class="card-text">{{post.title}}</p>
              </div>
            </div>
          </a>
        </div>
        {% endfor %}
        {% else %}
        
        <div class="col-12 col-sm-6 col-md-4 col-lg-4">
          <a href="#" class="text-underline-none">
            <div class="card custom-card">
              <img src="{% static 'Blog/images/Blog_page_compress.jpg' %}" class="card-img-top" alt="..." loading="lazy">
              <div class="card-body">
                <p class="card-text">Lakes in Virginia and Hampton</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-4">
          <a href="#" class="text-underline-none">
            <div class="card custom-card">
              <img src="{% static 'Blog/images/Blog_page_compress.jpg' %}" class="card-img-top" alt="..." loading="lazy">
              <div class="card-body">
                <p class="card-text">Lakes in Virginia and Hampton</p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-4">
          <a href="#" class="text-underline-none">
            <div class="card custom-card">
              <img src="{% static 'Blog/images/Blog_page_compress.jpg' %}" class="card-img-top" alt="..." loading="lazy">
              <div class="card-body">
                <p class="card-text">Lakes in Virginia and Hampton</p>
              </div>
            </div>
          </a>
        </div>
        {% endif %}
       
        <!-- Repeat for additional cards -->
      </div>
</div>


<!-- Popular Guides -->
<div class="heading-container mt-5 mb-5">
  <h1 class="heading">Popular Guides</h1>
</div>
<div class="container">
  <div class="row gx-4 gy-3">
    {% if popular_guides %}
       {% for guide in popular_guides %}
       <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <a href="{% url 'Blog:blog_detail' guide.slug %}" class="text-underline-none">
          <div class="card" >
            {% if guide.popular_image.image.url %}
            <img src="{{guide.popular_image.image.url}}" class="card-img-top-guides" alt="..." loading="lazy">   
            
            {% else %}
            <img src="{{guide.main_image.url}}" class="card-img-top-guides" alt="..."> 
            {% endif %}
            <div class="card-body">
              <p class="card-text text-center">{{guide.title}}</p>
            </div>
          </div>
        </a>
      </div>
       {% endfor %}
    {% else %}

    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <a href="#" class="text-underline-none">
        <div class="card" >
          <img src="{% static 'Blog/images/rumvia_compress.jpg' %}" class="card-img-top-guides" alt="..." loading="lazy">   
          <div class="card-body">
            <p class="card-text text-center">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <a href="#" class="text-underline-none">
        <div class="card" >
          <img src="{% static 'Blog/images/rumvia_compress.jpg' %}" class="card-img-top-guides" alt="..." loading="lazy">
          <div class="card-body">
            <p class="card-text text-center">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <a href="#" class="text-underline-none">
        <div class="card" >
          <img src="{% static 'Blog/images/rumvia_compress.jpg' %}" class="card-img-top-guides" alt="..." loading="lazy">
          

          <div class="card-body">
            <p class="card-text text-center">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <a href="#" class="text-underline-none">
        <div class="card">
          <img src="{% static 'Blog/images/rumvia_compress.jpg' %}" class="card-img-top-guides" alt="..." loading="lazy">
        

          <div class="card-body">
            <p class="card-text text-center">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </a>
    </div>
    {% endif %}
    <!-- Repeat for additional cards -->
  </div>
</div>



<div class="text-center mt-5 p-4 ">
  <h3 class="f" style="font-size: 22px;">Newsletter</h3>
  <p>Subscribe to my newsletter for the latest blog posts, tips, & travel guides. Let's stay updated!</p>
  <form action="" id="email_newsletter">
  <div class="row gx-0">
    <div class="col-md-3"></div>
    <div class="col-sm-12 col-md-5">
      <input type="email" name="email" placeholder="Email...." class="form-control mw-75 mb-2 mb-lg-0 email-input">
    </div>
    <div class="col-sm-12 col-md-2">

      <button type="submit" class="btn bg-dark text-white w-100 m w-lg-25 subscribe-btn ">Subscribe</button>
    </div>
  </div>
</form>
</div>

{% endblock content %}



{% block js %}
<script>

  $(document).ready(function() {
    $("#email_newsletter").submit(function(e){
         e.preventDefault()
         console.log('email')
         var formdata = {
          email : $("input[name='email']").val()
         };

        $.ajax({
          url : "/email_newsletter/",
          type: 'POST',
          data : formdata,
          headers: {
        "X-CSRFToken": "{{ csrf_token }}", // Add CSRF token for security if using Django
      },

      success : function(response){
        $("#email_newsletter").trigger('reset')
        Toastify({
            text: response.message,
            duration: 1500,
            close: true,
            gravity: "top", // `top` or `bottom`
            position: "right", // `left`, `center` or `right`
            backgroundColor: "linear-gradient(to right, #00b09b, #96c93d)",
          }).showToast();
      },

      error: function(xhr, status, error) {
        Toastify({
            text: xhr.responseJSON.error || "An error occurred", // Use error message from server if available
            duration: 1500,
            close: true,
            gravity: "center",
            position: "center",
            backgroundColor: "linear-gradient(to right, #ff5f6d, #ffc371)", // Adjust for error
        }).showToast();
    }
        }) 
    })

  })
</script>

{% endblock js %}

Blog/templates/Blog/nested_replies.html
<!-- nested_replies.html -->
{% for reply in replies %}
    <div class="reply-box ms-4 mt-3" id="reply-{{ reply.id }}">
        <div class="d-flex align-items-center">
            <strong>{{ reply.name }}</strong>
            <button class="btn btn-link ms-auto" type="button" data-bs-toggle="collapse"
                data-bs-target="#reply-form-{{ reply.id }}" aria-expanded="false" aria-controls="reply-form-{{ reply.id }}">
                Reply
            </button>
        </div>
        <p>{{ reply.comment_text }}</p>
        <small class="">{{ reply.created_at }}</small>

        <!-- Nested Reply Form -->
        <div id="reply-form-{{ reply.id }}" class="accordion-collapse collapse" aria-labelledby="reply-{{ reply.id }}">
            <div class="accordion-body">
                <form class="reply-form" data-comment-id="{{ reply.id }}">
                    <input type="hidden" name="comment_id" value="{{ reply.id }}" />
                    <input type="hidden" name="post_id" value="{{ blog.id }}" />
                    <div class="mb-3">
                        <textarea name="comment" rows="3" class="form-control" placeholder="Write your reply here..." required></textarea>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" name="name" class="form-control" placeholder="Your Name" required />
                        </div>
                        <div class="col-md-6">
                            <input type="email" name="email" class="form-control" placeholder="Your Email" required />
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Post Reply</button>
                </form>
            </div>
        </div>

        <!-- Recursively Include Replies -->
        <div class="reply-list ms-4 mt-3">
        {% if reply.replies.all %}
            {% include 'Blog/nested_replies.html' with replies=reply.replies.all %}
        {% endif %}
        </div>
    </div>
{% endfor %}