Blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Blog"

urlpatterns = [
    path('', views.home_page,name='home_page'),
    path('email_newsletter/',views.emailNewsletter,name='email'),
    path('blog_page/',views.blog_page,name='blog_page'),
    path('blog_detail/<slug:slug>/',views.blog_detail,name='blog_detail'),
    path('search/', views.search, name='search'),
    path('add_comment/',views.add_comment,name='add_comment'),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('category/<slug:slug>/', views.blog_by_category, name='blog_by_category'),
    path('destination/<slug:slug>/', views.blog_by_destination, name='blog_by_destination'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('',include('Blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/footer.html
<footer class="mt-5" style="background-color: var(--primary-color);">
      <div class="text-white text-center p-3">
            <a href="" class="p-2"><i class="fa-brands fa-facebook"></i></a>
            <a href="" class="p-2"><i class="fa-brands fa-instagram"></i></a>
            <a href="" class="p-2"><i class="fa-brands fa-youtube"></i></a>
            <a href="" class="p-2"><i class="fa-brands fa-pinterest-p"></i></a>
            <p class="mt-3">© Rumvia </p>
            <a href="" class="text-decoration-none">Affilliate Disclouser</a>
            • 
            <a href="" class="text-decoration-none">privacry Policy</a>
            • 
            <a href="" class="text-decoration-none">Terms of Use</a>
            <br>
            <br>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique quis, repellat fugit tempora ab aut! Nobis ullam distinctio magnam exercitationem laboriosam? Placeat eaque facilis quaerat rem laboriosam beatae odio tempora!</p>
      </div>
      <div></div>
      <div></div>
      <div></div>
</footer>

templates/header.html
<div class="container">
    <nav style="margin-bottom: 20px;">
        <div class="navbar">
            <i class='bx bx-menu'></i>
            <div class="logo"><a href="{% url "Blog:home_page" %}">Rumvia</a></div>
            <div class="nav-links">
                <div class="sidebar-logo">
                    <span class="logo-name">Rumvia</span>
                    <i class='bx bx-x'></i>
                </div>
                <ul class="links">
                    <li><a href="{% url "Blog:home_page" %}" class="{% if request.path == '/' %}active{% endif %}">HOME</a></li>
                    <li><a href="{% url "Blog:blog_page" %}" class="{% if request.path == '/blog_page/' %}active{% endif %}">BLOGS</a></li>




                    <li>
                        <a href="#">Categories</a>
                        <i class='bx bxs-chevron-down htmlcss-arrow arrow'></i>
                        <ul class="htmlCss-sub-menu sub-menu">
                            {% for category in categories %}
                            {% if category.subcategories.all %}
                            <!-- Category with subcategories -->
                            <li class="more">
                                <span>
                                    <a href="{% url 'Blog:blog_by_category' category.slug %}">{{ category.name }}</a>
                                    <i class='bx bxs-chevron-right arrow more-arrow'></i>
                                </span>
                                <ul class="more-sub-menu sub-menu">
                                    {% for subcategory in category.subcategories.all %}
                                    <li><a href="{% url 'Blog:blog_by_category' subcategory.slug %}">{{ subcategory.name}}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% else %}
                            <!-- Category without subcategories -->
                            <li>
                                <a href="{% url 'Blog:blog_by_category' category.slug %}">{{ category.name }}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </li>









                    <li>
                        <a href="#">Destinations</a>
                        <i class='bx bxs-chevron-down js-arrow arrow'></i>
                        <ul class="js-sub-menu sub-menu">
                            {% for destination in destinations %}
                            {% if destination.sub_destinations.all %}
                            <!-- Destination with sub-destinations -->
                            <li class="more">
                                <span>
                                    <a href="{% url 'Blog:blog_by_destination' destination.slug %}">{{ destination.name}}</a>
                                    <i class='bx bxs-chevron-right arrow more-arrow'></i>
                                </span>
                                <ul class="more-sub-menu sub-menu">
                                    {% for subdestination in destination.sub_destinations.all %}
                                    <li><a href="{% url 'Blog:blog_by_destination' subdestination.slug %}">{{subdestination.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% else %}
                            <!-- Destination without sub-destinations -->
                            <li>
                                <a href="{% url 'Blog:blog_by_destination' destination.slug %}">{{ destination.name}}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </li>

                    <li><a href="{% url "Blog:about" %}">ABOUT US</a></li>
                    {% comment %} <li><a href="{% url " Blog:contact" %}">CONTACT US</a></li> {% endcomment %}
                    <li>
                        <a href="{% url 'Blog:contact' %}" class="{% if request.path == '/contact/' %}active{% endif %}">Contact</a>
                    </li>
                </ul>
            </div>
            <form method="get" action="{% url 'Blog:search' %}">
                <div class="search-box">
                    <i class='bx bx-search'></i>
                    <div class="input-box">
                        <input type="text" name="query" placeholder="Search..." value="{{query}}" required>
                    </div>
                </div>
            </form>

        </div>
    </nav>
</div>